name: wozle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.5
  firebase_crashlytics: ^3.0.16
  device_info_plus: ^8.1.0
  logger: ^1.3.0
  package_info_plus: ^3.0.3
  get: ^4.6.5
  syncfusion_flutter_charts: ^21.1.37
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 400

  assets:
    - assets/imgs/
    - assets/icons/
