import 'package:flutter/material.dart';

const ColorScheme appColorSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xff748bac),
  onPrimary: Color(0xfff8f9fc),
  primaryContainer: Color(0xff1b2e4b),
  onPrimaryContainer: Color(0xffe4e7eb),
  secondary: Color(0xff539eaf),
  onSecondary: Color(0xfff5fbfc),
  secondaryContainer: Color(0xff004e5d),
  onSecondaryContainer: Color(0xffdfecee),
  tertiary: Color(0xff219ab5),
  onTertiary: Color(0xfff1fbfd),
  tertiaryContainer: Color(0xff0f5b6a),
  onTertiaryContainer: Color(0xffe2eef0),
  error: Color(0xffcf6679),
  onError: Color(0xff140c0d),
  errorContainer: Color(0xffb1384e),
  onErrorContainer: Color(0xfffbe8ec),  
  background: Color(0xff16181a),
  onBackground: Color(0xffececed),
  surface: Color(0xff16181a),
  onSurface: Color(0xffececed),
  surfaceVariant: Color(0xff1c1f23),
  onSurfaceVariant: Color(0xffdbdbdc),
  outline: Color(0xff9d9da3),  
  shadow: Color(0xff000000),
  inverseSurface: Color(0xfff6f8fa),
  onInverseSurface: Color(0xff131313),
  inversePrimary: Color(0xff404b59),
  surfaceTint: Color(0xff748bac),
);
