import 'package:flutter/material.dart';

const textThemeDark = TextTheme(
  displayLarge: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 57,
    fontWeight: FontWeight.w400,
  ),
  displayMedium: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 45,
    fontWeight: FontWeight.w400,
  ),
  displaySmall: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 36,
    fontWeight: FontWeight.w400,
  ),
  headlineLarge: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 32,
    fontWeight: FontWeight.w400,
  ),
  headlineMedium: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 28,
    fontWeight: FontWeight.w400,
  ),
  headlineSmall: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 24,
    fontWeight: FontWeight.w400,
  ),
  titleLarge: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.0,
    fontSize: 22,
    fontWeight: FontWeight.w400,
  ),
  titleMedium: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.15,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.1,
    fontSize: 14,
    fontWeight: FontWeight.w500,
  ),
  labelLarge: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.1,
    fontSize: 14,
    fontWeight: FontWeight.w500,
  ),
  labelMedium: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.5,
    fontSize: 12,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.5,
    fontSize: 11,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.15,
    fontSize: 16,
    fontWeight: FontWeight.w400,
  ),
  bodyMedium: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.25,
    fontSize: 14,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: TextStyle(
    fontFamily: "Montserrat",
    color: Colors.black,
    letterSpacing: 0.4,
    fontSize: 12,
    fontWeight: FontWeight.w400,
  ),
);
